# Intro to Pandas

### Why Pandas? What is it?

In [77]:
import pandas as pd

In [78]:
pokemon = pd.read_csv('data/pokemon.csv')

In [79]:
pokemon.describe()

,#,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation
count,800.000000,800.00000,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.00000
mean,362.813750,435.10250,69.258750,79.001250,73.842500,72.820000,71.902500,68.277500,3.32375
std,208.343798,119.96304,25.534669,32.457366,31.183501,32.722294,27.828916,29.060474,1.66129
min,1.000000,180.00000,1.000000,5.000000,5.000000,10.000000,20.000000,5.000000,1.00000
25%,184.750000,330.00000,50.000000,55.000000,50.000000,49.750000,50.000000,45.000000,2.00000
50%,364.500000,450.00000,65.000000,75.000000,70.000000,65.000000,70.000000,65.000000,3.00000
75%,539.250000,515.00000,80.000000,100.000000,90.000000,95.000000,90.000000,90.000000,5.00000
max,721.000000,780.00000,255.000000,190.000000,230.000000,194.000000,230.000000,180.000000,6.00000

In [80]:
pokemon_2 = pokemon.copy()
pokemon_2['Total Atk'] =  pokemon_2['Attack'] + pokemon_2['Sp. Atk']

In [81]:
pokemon_2.groupby('Legendary').mean()

,#,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Total Atk
Legendary,,,,,,,,,,
False,353.315646,417.213605,67.182313,75.669388,71.559184,68.454422,68.892517,65.455782,3.284354,144.123810
True,470.215385,637.384615,92.738462,116.676923,99.661538,122.184615,105.938462,100.184615,3.769231,238.861538

In [82]:
pokemon_2.sort_values(by = ['Attack','HP'],ascending = [False,True])

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total Atk
163,150,MewtwoMega Mewtwo X,Psychic,Fighting,780,106,190,100,154,100,130,1,True,344
232,214,HeracrossMega Heracross,Bug,Fighting,600,80,185,115,40,105,75,2,False,225
429,386,DeoxysAttack Forme,Psychic,NaN,600,50,180,20,180,20,150,3,True,360
424,383,GroudonPrimal Groudon,Ground,Fire,770,100,180,160,150,90,90,3,True,330
426,384,RayquazaMega Rayquaza,Dragon,Flying,780,105,180,100,180,100,115,3,True,360
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
139,129,Magikarp,Water,NaN,200,20,10,55,15,20,80,1,False,25
230,213,Shuckle,Bug,Rock,505,20,10,230,10,230,5,2,False,20
261,242,Blissey,Normal,NaN,540,255,10,10,75,135,55,2,False,85
488,440,Happiny,Normal,NaN,220,100,5,5,15,65,30,4,False,20
121,113,Chansey,Normal,NaN,450,250,5,5,35,105,50,1,False,40

In [83]:
the_filter = pokemon['Total'] >= 500

In [84]:
pokemon.where(the_filter,'Weak Pokemon')

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,Weak Pokemon,Weak Pokemon,Weak Pokemon,Weak Pokemon,Weak Pokemon,Weak Pokemon,Weak Pokemon,Weak Pokemon,Weak Pokemon,Weak Pokemon,Weak Pokemon,Weak Pokemon,Weak Pokemon
1,Weak Pokemon,Weak Pokemon,Weak Pokemon,Weak Pokemon,Weak Pokemon,Weak Pokemon,Weak Pokemon,Weak Pokemon,Weak Pokemon,Weak Pokemon,Weak Pokemon,Weak Pokemon,Weak Pokemon
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,Weak Pokemon,Weak Pokemon,Weak Pokemon,Weak Pokemon,Weak Pokemon,Weak Pokemon,Weak Pokemon,Weak Pokemon,Weak Pokemon,Weak Pokemon,Weak Pokemon,Weak Pokemon,Weak Pokemon
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [86]:
pokemon[the_filter]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
6,6,Charizard,Fire,Flying,534,78,84,78,109,85,100,1,False
7,6,CharizardMega Charizard X,Fire,Dragon,634,78,130,111,130,85,100,1,False
8,6,CharizardMega Charizard Y,Fire,Flying,634,78,104,78,159,115,100,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [87]:
pokemon_aggregator = pokemon.copy()

In [89]:
pokemon_aggregator.groupby(['Type 1','Type 2']).mean()

                          #       Total         HP      Attack     Defense  \
Type 1 Type 2
Bug    Electric  595.500000  395.500000  60.000000   62.000000   55.000000
       Fighting  214.000000  550.000000  80.000000  155.000000   95.000000
       Fire      636.500000  455.000000  70.000000   72.500000   60.000000
       Flying    286.285714  419.500000  63.000000   70.142857   61.571429
       Ghost     292.000000  236.000000   1.000000   90.000000   45.000000
...                     ...         ...        ...         ...         ...
Water  Ice       103.000000  511.666667  90.000000   83.333333  113.333333
       Poison    118.666667  426.666667  61.666667   68.333333   58.333333
       Psychic   111.800000  481.000000  87.000000   73.000000  104.000000
       Rock      430.000000  428.750000  70.750000   82.750000  112.750000
       Steel     395.000000  530.000000  84.000000   86.000000   88.000000

                    Sp. Atk     Sp. Def      Speed  Generation  Legendary
Type 1 Type 2
Bug    Electric   77.000000   55.000000  86.500000    5.000000        0.0
       Fighting   40.000000  100.000000  80.000000    2.000000        0.0
       Fire       92.500000   80.000000  80.000000    5.000000        0.0
       Flying     72.857143   69.071429  82.857143    2.857143        0.0
       Ghost      30.000000   30.000000  40.000000    3.000000        0.0
...                     ...         ...        ...         ...        ...
Water  Ice        80.000000   78.333333  66.666667    1.000000        0.0
       Poison     61.666667   91.666667  85.000000    1.333333        0.0
       Psychic    94.000000   79.000000  44.000000    1.200000        0.0
       Rock       61.500000   65.000000  36.000000    3.750000        0.0
       Steel     111.000000  101.000000  60.000000    4.000000        0.0

[136 rows x 10 columns]

In [91]:
pokemon_aggregator.groupby(['Type 1']).mean().sort_values(by=['Total'],ascending = False)

,#,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
Type 1,,,,,,,,,,
Dragon,474.375000,550.531250,83.312500,112.125000,86.375000,96.843750,88.843750,83.031250,3.875000,0.375000
Steel,442.851852,487.703704,65.222222,92.703704,126.370370,67.518519,80.629630,55.259259,3.851852,0.148148
Flying,677.750000,485.000000,70.750000,78.750000,66.250000,94.250000,72.500000,102.500000,5.500000,0.500000
Psychic,380.807018,475.947368,70.631579,71.456140,67.684211,98.403509,86.280702,81.491228,3.385965,0.245614
Fire,327.403846,458.076923,69.903846,84.769231,67.769231,88.980769,72.211538,74.442308,3.211538,0.096154
Rock,392.727273,453.750000,65.363636,92.863636,100.795455,63.340909,75.477273,55.909091,3.454545,0.090909
Dark,461.354839,445.741935,66.806452,88.387097,70.225806,74.645161,69.516129,76.161290,4.032258,0.064516
Electric,363.500000,443.409091,59.795455,69.090909,66.295455,90.022727,73.704545,84.500000,3.272727,0.090909
Ghost,486.500000,439.562500,64.437500,73.781250,81.187500,79.343750,76.468750,64.343750,4.187500,0.062500
Ground,356.281250,437.500000,73.781250,95.750000,84.843750,56.468750,62.750000,63.906250,3.156250,0.125000
Ice,423.541667,433.458333,72.000000,72.750000,71.416667,77.541667,76.291667,63.458333,3.541667,0.083333
Water,303.089286,430.455357,72.062500,74.151786,72.946429,74.812500,70.517857,65.964286,2.857143,0.035714
Grass,344.871429,421.142857,67.271429,73.214286,70.800000,77.500000,70.428571,61.928571,3.357143,0.042857
Fighting,363.851852,416.444444,69.851852,96.777778,65.925926,53.111111,64.703704,66.074074,3.370370,0.000000
Fairy,449.529412,413.176471,74.117647,61.529412,65.705882,78.529412,84.705882,48.588235,4.117647,0.058824
Normal,319.173469,401.683673,77.275510,73.469388,59.846939,55.816327,63.724490,71.551020,3.051020,0.020408
Poison,251.785714,399.142857,67.250000,74.678571,68.821429,60.428571,64.392857,63.571429,2.535714,0.000000
Bug,334.492754,378.927536,56.884058,70.971014,70.724638,53.869565,64.797101,61.681159,3.217391,0.000000

In [95]:
pokemon_aggregator.groupby(['Type 1']).agg(['max','min','mean']).sort_values(by=[('Total','mean')],ascending = False)

pokemon_agg_dict = {
    '#':[],
    'Total':['max','mean','min']
}

/tmp/ipykernel_220499/4263858404.py:1: FutureWarning: ['Name', 'Type 2'] did not aggregate successfully. If any error is raised this will raise in a future version of pandas. Drop these columns/ops to avoid this warning.
  pokemon_aggregator.groupby(['Type 1']).agg(['max','min','mean']).sort_values(by=[('Total','mean')],ascending = False)

            #                  Total                    HP                 \
          max  min        mean   max  min        mean  max min       mean
Type 1
Dragon    718  147  474.375000   780  300  550.531250  125  41  83.312500
Steel     707  208  442.851852   700  300  487.703704  100  40  65.222222
Flying    715  641  677.750000   580  245  485.000000   85  40  70.750000
Psychic   720   63  380.807018   780  198  475.947368  190  20  70.631579
Fire      721    4  327.403846   680  250  458.076923  115  38  69.903846
Rock      719   74  392.727273   700  280  453.750000  123  30  65.363636
Dark      717  197  461.354839   680  220  445.741935  126  35  66.806452
Electric  702   25  363.500000   610  205  443.409091   90  20  59.795455
Ghost     711   92  486.500000   680  275  439.562500  150  20  64.437500
Ground    645   27  356.281250   770  265  437.500000  115  10  73.781250
Ice       713  124  423.541667   580  250  433.458333  110  36  72.000000
Water     693    7  303.089286   770  200  430.455357  170  20  72.062500
Grass     673    1  344.871429   630  180  421.142857  123  30  67.271429
Fighting  701   56  363.851852   625  210  416.444444  144  30  69.851852
Fairy     716   35  449.529412   680  218  413.176471  126  35  74.117647
Normal    676   16  319.173469   720  190  401.683673  255  30  77.275510
Poison    691   23  251.785714   535  245  399.142857  105  35  67.250000
Bug       666   10  334.492754   600  194  378.927536   86   1  56.884058

         Attack  ...    Sp. Def Speed                 Generation      \
            max  ...       mean   max min        mean        max min
Type 1           ...
Dragon      180  ...  88.843750   120  40   83.031250          6   1
Steel       150  ...  80.629630   110  23   55.259259          6   2
Flying      115  ...  72.500000   123  55  102.500000          6   5
Psychic     190  ...  86.280702   180  20   81.491228          6   1
Fire        160  ...  72.211538   126  20   74.442308          6   1
Rock        165  ...  75.477273   150  10   55.909091          6   1
Dark        150  ...  69.516129   125  20   76.161290          6   2
Electric    123  ...  73.704545   140  35   84.500000          6   1
Ghost       165  ...  76.468750   130  20   64.343750          6   1
Ground      180  ...  62.750000   120  10   63.906250          5   1
Ice         130  ...  76.291667   110  25   63.458333          6   1
Water       155  ...  70.517857   122  15   65.964286          6   1
Grass       132  ...  70.428571   145  10   61.928571          6   1
Fighting    145  ...  64.703704   118  25   66.074074          6   1
Fairy       131  ...  84.705882    99  15   48.588235          6   1
Normal      160  ...  63.724490   135   5   71.551020          6   1
Poison      106  ...  64.392857   130  25   63.571429          6   1
Bug         185  ...  64.797101   160   5   61.681159          6   1

                   Legendary
              mean       max    min      mean
Type 1
Dragon    3.875000      True  False  0.375000
Steel     3.851852      True  False  0.148148
Flying    5.500000      True  False  0.500000
Psychic   3.385965      True  False  0.245614
Fire      3.211538      True  False  0.096154
Rock      3.454545      True  False  0.090909
Dark      4.032258      True  False  0.064516
Electric  3.272727      True  False  0.090909
Ghost     4.187500      True  False  0.062500
Ground    3.156250      True  False  0.125000
Ice       3.541667      True  False  0.083333
Water     2.857143      True  False  0.035714
Grass     3.357143      True  False  0.042857
Fighting  3.370370     False  False  0.000000
Fairy     4.117647      True  False  0.058824
Normal    3.051020      True  False  0.020408
Poison    2.535714     False  False  0.000000
Bug       3.217391     False  False  0.000000

[18 rows x 30 columns]